//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeWorkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CompanyCategories = new HashSet<CompanyCategory>();
            this.GroupCategories = new HashSet<GroupCategory>();
        }
    
        public int categoryId { get; set; }
        public string categoryName { get; set; }
        public string categoryDescription { get; set; }
    
        public virtual ICollection<CompanyCategory> CompanyCategories { get; set; }
        public virtual ICollection<GroupCategory> GroupCategories { get; set; }
    }
}
