//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeWorkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupCategories = new HashSet<GroupCategory>();
            this.PersonGroups = new HashSet<PersonGroup>();
        }
    
        public int groupId { get; set; }
        public string groupName { get; set; }
        public string website { get; set; }
        public string address { get; set; }
        public string mailingList { get; set; }
        public string description { get; set; }
        public string meetingInfo { get; set; }
        public string tags { get; set; }
        public string technologies { get; set; }
        public string logo { get; set; }
    
        public virtual ICollection<GroupCategory> GroupCategories { get; set; }
        public virtual ICollection<PersonGroup> PersonGroups { get; set; }
    }
}
